### ISSUE TITLE
[Feat] usePath 커스텀 훅 제작

### ISSUE THREAD

**Issue by pildrums** [Team-TMB/client#17]
### 📌 Description

클래스 이름 및 pathname을 한 곳에서 사용하기 위한 커스텀 훅 제작

### 📝 ToDo

작업을 위한 ToDoList를 작성해주세요.

- [X] match 경로에 대한 active 클래스 변수 작업
- [X] 라우팅 시 언더바 출력 클래스 변수 작업
- [X] 경로 변수 작업
- [X] 커스텀 훅 리팩토링
