### ISSUE TITLE
[Refactor] Title, Text 컴포넌트 리팩토링 완료

### ISSUE THREAD

**Issue by pildrums** [Team-TMB/client#21]
### 📌 Description

Title, Text 컴포넌트 리팩토링 및 classnames 라이브러리로 조건부 렌더링 작업

### 📝 ToDo

작업을 위한 ToDoList를 작성해주세요.

- [X] 나눠져 있는 Title 컴포넌트를 하나로 합치는 작업
- [X] 나눠져 있는 Text 컴포넌트를 하나로 합치는 작업
- [X] 클래스 이름의 언더바를 하이픈으로 고치는 작업
- [X] classnames 라이브러리로 조건부 렌더링 작업 (props로 전달해서 조건부 스타일링 가능)
