### ISSUE TITLE
[Feature] 좋아요 기능 구현 및 mutate 함수 이름 변경, 기타 사항

### ISSUE THREAD

**Issue by sihyun92** [Team-TMB/client#63]
### 📌 Description

작업에 대한 설명을 작성해주세요

### 📝 ToDo
- 댓글 좋아요 API 함수 작성 완료했습니다.
- useQuery로 받아오는 data 변수의 이름을 각 기능에 맞게 수정했습니다 (ex. data -> data: todayData)
- useMutation에서 받아오는 mutate 함수도 기능에 맞게 수정했습니다 (ex. mutate -> mutate: removeComment)
- CommentData도 댓글 조회 API Response 값의 변경에 따라 interface 수정 완료했습니다.

작업을 위한 ToDoList를 작성해주세요.

- [X] CommentData 인터페이스 내용 변경
- [X] 댓글 좋아요 API 함수 작성
- [X] mutate 함수 각 기능에 맞게 이름 변경
- [X] useQuery로 받아오는 data 변수 각 용도에 맞게 이름 변경
- [ ] 좋아요 / 취소 기능 구현
- [ ]  오늘의 승부예측 투표 토글 기능 구현
