### ISSUE TITLE
[Feat] 댓글 입력창 빈 value값 오류 처리

### ISSUE THREAD

**Issue by sihyun92** [Team-TMB/client#69]
### 📌 Description

댓글 입력창이 빈 상태로 submit을 할 경우 오류메시지 출력

### 📝 ToDo

작업을 위한 ToDoList를 작성해주세요.

- [X] Comment submit 오류 처리
- [X] 댓글 좋아요 취소 API 함수 구현
- [ ] 대댓글 구현
- [X] 좋아요 버튼 클릭 애니메이션 구현
- [X] 각 경기 남은 시간 카운트 UI 구현
- [ ] 각 경기 남은 시간 카운트 기능 구현
