### ISSUE TITLE
[Design] 마이페이지 UI 작업

### ISSUE THREAD

**Issue by doitidey** [Team-TMB/client#74]
### 📌 Description

마이페이지 UI 작업을 진행합니다.

### 📝 ToDo

- [x] 프로필 박스 컴포넌트
- [x] 요정기록 컴포넌트
- [x] 선물 기록 컴포넌트
- [x] 수정 가능
- [x] 팀 선택 페이지 이동
