### ISSUE TITLE
[Fix] 댓글 UI 변경

### ISSUE THREAD

**Issue by sihyun92** [Team-TMB/client#84]
### 📌 Description

UI 디자인의 변경에 따라 수정.

### 📝 ToDo

작업을 위한 ToDoList를 작성해주세요.

- [X] input을 textarea로 변경
- [X] 댓글 창 색상 변경
- [X] 댓글 입력 줄에 따라 textarea 변경 (autosize 라이브러리)
- [X] 글자 수 입력 제한 기능 구현
- [X] 엔터 키 입력 방지 (textarea 태그는 엔터로 submit 불가능)
