### ISSUE TITLE
[Feat] 마이페이지 api 연동

### ISSUE THREAD

**Issue by doitidey** [Team-TMB/client#90]
### 📌 Description

마이페이지에 필요한 api를 연동합니다.

### 📝 ToDo
- [x] 수정된 데이터 Put
- [x] 팀 수정 put
- [x] 요정 기록 get
- [x] 선물 내역 get
